version: 2.1
orbs:
    core: vanilla/core@2.2.3
    jobs: vanilla/jobs@1
jobs:
    php_sphinx_tests:
        executor: core/sphinx
        steps:
            - attach_workspace:
                at: ~/workspace
            - core/checkout
            - run: ~/workspace/ci-scripts/clone-vanilla.sh
            - core/composer_install
            - core/prepare_php_tests
            - core/prepare_sphinx
            - core/run_sphinx_test_suite
    frontend_setup:
        executor: core/node
        steps:
            - run:
                name: Versions
                command: |
                  node --version
                  yarn --version
            - core/checkout
            - run:
                name: Clone Vanilla Repo
                command: ~/workspace/ci-scripts/clone-vanilla.sh
            - run:
                # Makes workspace persisting much faster if not needed.
                name: Cleaning up git directory
                command: |
                    cd ~/workspace/vanilla
                    rm -rf .git
                    # We explcitly don't cache dependencies.
                    # The cache validation & fetching seems to take longer than fetching from source.
            - run:
                name: Install Yarn Packages
                command: |
                    cd ~/workspace/vanilla
                    yarn install --pure-lockfile
                    yarn install-all
            - persist_to_workspace:
                root: ~/workspace
                paths:
                  - repo
                  - ci-scripts
                  - vanilla
workflows:
    version: 2.1
    commit:
        jobs:
            # PHP 7.2 jobs are only nightly until we move upwards on infra.
            - jobs/php_setup:
                  name: php_setup
            - jobs/php_72_lint
            - php_sphinx_tests
            - jobs/php_72_tests:
                  requires:
                      - php_setup
            # JS and browsers
            - frontend_setup
            - jobs/frontend_lint:
                  requires:
                      - frontend_setup
            - jobs/frontend_typechecker:
                  requires:
                      - frontend_setup
            - jobs/frontend_build:
                  requires:
                      - frontend_setup
            - jobs/frontend_test:
                  requires:
                      - frontend_setup
    nightly:
        triggers:
            - schedule:
                  cron: "0 0 * * *" # Once a day.
                  filters:
                      branches:
                          only:
                              - master
        jobs:
            - jobs/dependency_audit
            # PHP and serverside
            - php_sphinx_tests
            - jobs/php_setup:
                  name: php_setup
            - jobs/php_72_lint
            - jobs/php_73_lint
            - jobs/php_72_tests:
                  requires:
                      - php_setup
            - jobs/php_73_tests:
                  requires:
                      - php_setup
            ## JS & browsers
            - jobs/frontend_setup:
                  name: frontend_setup
            - jobs/frontend_lint:
                  requires:
                      - frontend_setup
            - jobs/frontend_typechecker:
                  requires:
                      - frontend_setup
            - jobs/frontend_build:
                  requires:
                      - frontend_setup
            - jobs/frontend_test:
                  requires:
                      - frontend_setup
